config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
  resources :clients
  resources :products

  root to: "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :user
  belongs_to :client
  has_many :quote_products, inverse_of: :quote
  has_many :products, through: :quote_products

  accepts_nested_attributes_for :quote_products, reject_if: :all_blank, allow_destroy: true
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
    @clients = Client.all
    @quote_products = @quote.quote_products.build
    @products = Product.all
  end

  # GET /quotes/1/edit
  def edit
    @clients = Client.all
    @products = Product.all
    @quote_products = @quote.quote_products
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @clients = Client.all
    @quote = Quote.new(quote_params)
    @quote.user = current_user

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:date_quote, :user_id, :client_id, quote_products_attributes:
        [
          :product_id,
          :quote_id,
          :qty,
          :product_price,
          :_destroy
        ]
      )
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<div class= "well bs-component">
  <%= form_with(model: quote, local: true, class: "form-horizontal") do |form| %>
    <fieldset>
      <% if quote.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

          <ul>
          <% quote.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :date_quote , class: "col-lg-2 control-label"%>
        <div class="col-lg-10">
          <%= form.text_field :date_quote, id: :quote_date_quote, class: "datepicker form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= form.label :client_id, class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= form.select :client_id, options_for_select(clients.map {|c| [c.fullname, c.id]}, form.object.client_id), {}, {class: "form-control"} %>
        </div>
      </div>

      <%= form.fields_for :quote_products do |build| %>

        <%= render partial: 'quote_product_fields', locals: {f: build, products: @products } %>
      <% end %>


      <div class='links'>
        <%= link_to_add_association 'Add Product', form, :quote_products, class: "btn btn-primary"%>
      </div>

      <div class="actions">
        <%= form.submit class: "btn btn-success"%>
      </div>

    </fieldset>
  <% end %>
</div>

app/views/quotes/_quote_product_fields.html.erb
<hr>
  <div class='nested-fields'>
    <div class="form-group">
      <%= f.label :product_id , class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= f.select :product_id, options_for_select(@products.map {|product| [product.name, product.id]}, f.object.product_id), {}, {class: "form-control"} %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :qty, class: "col-lg-2 control-label"  %>
      <div class="col-lg-10">
        <%= f.number_field :qty , class: "form-control"%>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <%= link_to_remove_association "remove product", f , class: "btn btn-danger"%>
      </div>
    </div>
  </div>

<script>
$('.datepicker').datepicker({
        language: 'es',
        endDate: '0'
});
$('select').select2({
    theme: "bootstrap"
});
</script>

app/views/quotes/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Editing Quote #<%= @quote.id%></h1>

    <%= render 'form', quote: @quote, clients: @clients %>

    <%= link_to 'Show', @quote, class: "btn btn-sm-default" %>
    <%= link_to 'Back', quotes_path, class: "btn btn-sm-default" %>
  </div>
</div>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<table class="table table-responsive">
  <thead>
    <tr>
      <th>Date quote</th>
      <th>User</th>
      <th>Client</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.date_quote %></td>
        <td><%= quote.user.name %></td>
        <td><%= quote.client.fullname %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>New Quote</h1>

    <%= render 'form', quote: @quote, clients: @clients %>

    <%= link_to 'Back', quotes_path, class: "btn btn-sm-default" %>
  </div>
</div>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date quote:</strong>
  <%= @quote.date_quote %>
</p>

<p>
  <strong>User:</strong>
  <%= @quote.user.name %>
</p>

<p>
  <strong>Client:</strong>
  <%= @quote.client.fullname %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>